### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by KinsNitor** [anime-kun32/AniTeams#18]
Whenever I try connecting my Aniwatch API link in the .env file or use it with links like Consumet, I keep getting errors like ‘error fetching episode data’ or missing images. It might just be me—could you please check and let me know if I’m doing something wrong?

**Comment by anime-kun32** [comment]
@anime-kun32

**Comment by anime-kun32** [comment]
@KinsNitor I have a look at it now

**Comment by anime-kun32** [comment]
Can you like share screenshot of your console logs and also for your network tab as well please

**Comment by anime-kun32** [comment]
And also make sure you have deployed your own version of the aniwatch api and the HiAnime mapper as well

**Comment by anime-kun32** [comment]
Please send me a sample url so I can figure this out

**Comment by anime-kun32** [comment]
Where did you deploy this and have also deployed your own version of the aniwatch api and consumer and the HiAnime mapper as well

**Comment by KinsNitor** [comment]
All to Vercel I will sent you the samples 
The Overall project : https://aniteamkez.vercel.app/
Aniwatch: theapianiapiqqq1.vercel.app
Mapper: themapperfiranimeyyy1.vercel.app
Consumet: api-consumet-org-lovat-one.vercel.app

**Comment by anime-kun32** [comment]
```env
NEXT_PUBLIC_API_BASE_URL=https://theapianiapiqqq1.vercel.app # https://github.com/ghoshRitesh12/aniwatch-api
NEXT_PUBLIC_CONSUMET_BASE_URL=https://api-consumet-org-lovat-one.vercel.app

NEXT_PUBLIC_ANILIST_CLIENT_ID=
NEXT_PUBLIC_DEPLOYMENT_URL=https://aniteamkez.vercel.app 
NEXT_PUBLIC_HIANIME_MAPPER_URL=https://themapperfiranimeyyy1.vercel.app  
# https://github.com/anime-kun32/hianime-mapper

NEXT_PUBLIC_ANILIST_CLIENT_SECRET=

```

**Comment by anime-kun32** [comment]
Update your env with those values and then make sure you set https://aniteamkez.vercel.app/ as an allowed origin for aniwatch and hianime mapper

**Comment by KinsNitor** [comment]
it shows everything but it just does not show the episode guide nor does it say an error i tried with anilist and without i think we made progress you can check the KinsNitor/AniTeamsdds the .env has it all

**Comment by anime-kun32** [comment]
Ok now go to anime-kun32/hianime-mapper 
 Make sure your deployment url is correct. Update your fork by syncing to the latest version, then edit the env file and then place this 

```env
ALLOWED_ORIGINS=https://aniteamkez.vercel.app
```

**Comment by KinsNitor** [comment]
https://aniteamkez.vercel.app/ Same problem you can check KinsNitor/AniTeamsdds and KinsNitor/hianimapeirt if i done something wrong , the mapper link is https://hianimapeirto00986.vercel.app/
i did the ALLOWED_ORIGINS=https://aniteamkez.vercel.app in .env anime-kun32/hianime-mapper and deployed it into vercel with the mapper link that you can check.

**Comment by anime-kun32** [comment]
Update your variable that should fix it

**Comment by KinsNitor** [comment]
Great the episodes now are shown but it doesnt play any nor does it show the dub or sub or the player.
https://aniteamkez.vercel.app/ again you can check, in anilist i put the redirect url as https://aniteamkez.vercel.app/ 

![Image](https://github.com/user-attachments/assets/a8d5592c-7582-4e71-88be-cef14f651a80)

![Image](https://github.com/user-attachments/assets/7493016e-73c6-4a69-8cac-641ec080a87b)

**Comment by anime-kun32** [comment]
Ok now for the anilist set the redirect URL to https://aniteamkez.vercel.app/callback

Can you give me the link to your aniwatch repo please

**Comment by KinsNitor** [comment]
https://github.com/[KinsNitor/theapianiapiqqq1](https://github.com/KinsNitor/theapianiapiqqq1/tree/main)/tree/main thats aniwatch the fork i the redirect https://aniteamkez.vercel.app/callback

**Comment by KinsNitor** [comment]
https://github.com/KinsNitor/theapianiapiqqq1 thats the AniWatch API, i changed the redirect to https://aniteamkez.vercel.app/callback in anilist.

**Comment by anime-kun32** [comment]
Ok go to your aniwatch repo and create a new .env  
 And then add this 

```env
ANIWATCH_API_CORS_ALLOWED_ORIGINS=https://aniteamkez.vercel.app

ANIWATCH_API_WINDOW_MS=1800000 
# maximum number of requests in this timeperiod
ANIWATCH_API_MAX_REQS=300

```

There you go that should fix it

**Comment by KinsNitor** [comment]
https://aniteamkez.vercel.app/ still the same problem, you can check the site and the repo of KinsNitor/AniTeamsdds and KinsNitor /theapianiapiqqq1

**Comment by anime-kun32** [comment]
```env
NEXT_PUBLIC_API_BASE_URL=https://theapianiapiqqq1.vercel.app
NEXT_PUBLIC_CONSUMET_BASE_URL=https://api-consumet-org-lovat-one.vercel.app
NEXT_PUBLIC_ANILIST_CLIENT_ID=26122
NEXT_PUBLIC_DEPLOYMENT_URL=https://aniteamkez.vercel.app 
NEXT_PUBLIC_HIANIME_MAPPER_URL=https://hianimapeirto00986.vercel.app
NEXT_PUBLIC_ANILIST_CLIENT_SECRET=TEl50acZW8OCzvt11gZKdd03pldzVcSp5UpIXXcX
```
Update your variables that should also fix the error

**Comment by anime-kun32** [comment]
```env

ANIWATCH_API_REDIS_CONN_URL=<rediss://default:your-secure-password@your-redis-instance-name.provider.com:6379>

# Cache-Control settings for Vercel Edge Caching
# Specifies the maximum amount of time (in seconds) a resource is considered fresh when served by a CDN cache.
ANIWATCH_API_S_MAXAGE=60
# Specifies the amount of time (in seconds) a resource is served stale while a new one is fetched.
ANIWATCH_API_STALE_WHILE_REVALIDATE=30

```
Remove that line from your env in your aniwatch api

**Comment by KinsNitor** [comment]
https://aniteamkez.vercel.app/watch/demon-slayer-kimetsu-no-yaiba-47?ep=1282&anilist=101922 again im sorry for talking for that long

**Comment by anime-kun32** [comment]
```env
NEXT_PUBLIC_API_BASE_URL=https://theapianiapiqqq1.vercel.app
```
Update this line make sure there is no slash at the end of the url

**Comment by KinsNitor** [comment]
this thank you now its all working im gonna close this chat have a good thanks for your time
